spring.application.name=EnterpriseStorageApplication

server.port = 8080

# Mongo DB
spring.data.mongodb.uri = mongodb://localhost:27017/storage_db

# Multipart
spring.servelet.multipart.enabled = true;
spring.servelet.multipart.max-file-size = 100MB
spring.servelet.multipart.max-request-size = 100MB

# Minio
app.storage.endpoint = http://localhost:9000
app.storage.access-key = admin
app.storage.secret-key = admin123
app.storage.region = us-east-1

# Swagger
springdoc.api-docs.path = /api-docs
springdoc.swagger-ui.path = /swagger-ui.html

# logging
logging.level.root = INFO
logging.level.com.webcom.storage = DEBUG
